# cpanm --installdeps .
requires 'Test::Perl::Critic', '>= 1.04';
requires 'Test::MinimumVersion', '>= 0.101083';
requires 'Test::Pod', '>= 1.52';
requires 'Test::DistManifest', '>= 1.014';
requires 'Capture::Tiny', '>= 0.48';
requires 'Data::Dump', '>= 1.25';
requires 'Devel::Cover', '>= 1.44';