# cpanm --installdeps .
# NOTE: Keep in sync with https://github.com/haukex/docker-perl-author-tests/blob/main/cpanfile
requires 'Test::Perl::Critic', '>= 1.04';
requires 'Test::MinimumVersion', '>= 0.101083';
requires 'Test::Pod', '>= 1.52';
requires 'Test::DistManifest', '>= 1.014';
requires 'Capture::Tiny', '>= 0.48';
requires 'Devel::Cover', '>= 1.44';
requires 'JSON::MaybeXS', '>= 1.004005';
requires 'Data::Dump', '>= 1.25';