language: perl
dist: trusty
perl:
    - "5.32"
    - "5.30"
    - "5.28"
    - "5.26"
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
    - "5.8"
#   - "5.6"  # not supported by Travis

# coveralls.io support:
before_install:
    # versions >1.33 fail on Perl <5.10
    - cpanm --notest Devel::Cover@1.33
    - cpanm --notest Devel::Cover::Report::Coveralls
after_success:
    # this will fail on Perl <5.10, but Travis doesn't report it as a failure
    # (it's ok if it fails, we don't need coverage reports from every single version)
    - cover -test -report coveralls
