# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: Basic Tests
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  tests:
    # Uses the Perl that comes preinstalled on all GH Action runners
    # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
    name: Default Perl on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: prove -l